"""
SahiRate Global Constants
"""

APP_NAME = "SahiRate"

COMPANY_CODE = "SR"

STATUS_ACTIVE = "ACTIVE"
STATUS_INACTIVE = "INACTIVE"
STATUS_PENDING = "PENDING"
STATUS_BLOCKED = "BLOCKED"
STATUS_DELETED = "DELETED"

ROLE_SUPER_ADMIN = "Super Admin"
ROLE_ADMIN = "Admin"
ROLE_MANAGER = "Manager"
ROLE_DEALER = "Dealer"
ROLE_CUSTOMER = "Customer"
